backend:
  name: git-gateway
  branch: master # nebo main, podle toho, jakou hlavní větev používáte

media_folder: "static/img" # Složka pro ukládání médií
public_folder: "/img"

collections:
  - name: "pages"
    label: "Stránky"
    files:
      - name: "home"
        label: "Úvodní Stránka"
        file: "src/content/home.md"
        fields:
          - {label: "Titulek", name: "title", widget: "string"}
          - {label: "Obsah", name: "body", widget: "markdown"}
      - name: "about"
        label: "O Nás"
        file: "src/content/about.md"
        fields:
          - {label: "Titulek", name: "title", widget: "string"}
          - {label: "Obsah", name: "body", widget: "markdown"}

  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    fields:
      - {label: "Název Projektu", name: "title", widget: "string"}
      - {label: "Popis", name: "description", widget: "text"}
      - {label: "Obrázek", name: "image", widget: "image"}
      - {label: "Kategorie", name: "category", widget: "string"}

  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    fields:
      - {label: "Název Článku", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Obsah", name: "body", widget: "markdown"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}
